// scripts/embed-version.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface PackageJson {
  version: string;
}

const pkgJsonPath = join(process.cwd(), "package.json");
const { version }: PackageJson = JSON.parse(readFileSync(pkgJsonPath, "utf8"));

const gitHash = process.env.npm_package_gitHead || "";

const resolvedVersion = gitHash ? `${version}-${gitHash}` : version;

const out = `/**
 * Auto-generated by scripts/embed-version.ts – do not edit.
 */
export const STAGEHAND_VERSION: string = '${resolvedVersion}';
`;

writeFileSync(join("lib", "__generated_version.ts"), out);
console.info(`▶︎ Embedded version ${resolvedVersion}`);
